services:
  nextapp:
    build:
      context: .
      target: development
    volumes:
      - ./app:/app/app
      - ./public:/app/public
      - nextapp_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    command: npm run dev
    depends_on:
      - backend

  backend:
    build:
      context: .
      target: development
    volumes:
      - ./backend:/app/backend
      - backend_venv:/usr/local/lib/python3.11/site-packages
    ports:
      - "8000:8000"
    command: sh -c "cd backend/beginners && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

volumes:
  nextapp_node_modules:
  backend_venv: