services:
  nextapp:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - backend

  backend:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: sh -c "cd backend/beginners && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - PYTHONUNBUFFERED=1