# Generated by Django 5.1.3 on 2024-11-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('tutorialTitle', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('tutorialBody', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('userpass', models.CharField(max_length=24)),
                ('isTeacher', models.BooleanField()),
            ],
        ),
    ]
